nipreps/mriqc

- mriqc/utils.py
> Extract BIDS bold task names as scan ids in fMRIQC

- mriqc/reports/utils.py
> Change size datatype from uint8 to uint16 for sizes > 256

- mriqc/utils/fs2gif.py
Improved fs2gif script (#65) to allow for new options in tkmedit, requested by Marie.
> [ENH] Improve fs2gif script

- mriqc/interfaces/qc.py
- mriqc/qc/anatomical.py
- mriqc/reports/generators.py
> [ENH] Add cjv measure

- mriqc/interfaces/qc.py
- mriqc/reports/generators.py
> Rename INU measures, compute range instead boundaries

- mriqc/interfaces/qc.py
Ref #5.
Tested on my desktop on the ds003_downsampled. It worked with python 3.5
> [FIX] Minor problem with tuple comparison

- mriqc/utils/mriqc_run.py
> [FIX] Fix race condition making work directory

- mriqc/utils/mriqc_run.py
- mriqc/workflows/core.py
> [FIX] mriqc crashes if no anatomical scans are found

- mriqc/workflows/anatomical.py
- requirements.txt
> [ENH] Move skull-stripping and reorient to NIworkflows

- CHANGES.txt
- mriqc/__init__.py
- mriqc/interfaces/__init__.py
- mriqc/interfaces/functional.py
- mriqc/qc/functional.py
- mriqc/workflows/functional.py
> [BUG] ComputeDVARS type error

- CHANGES.txt
- build/circle_tests.sh
- mriqc/__init__.py
- mriqc/utils/misc.py
- mriqc/utils/mriqc_run.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/core.py
- mriqc/workflows/functional.py
> [ENH] Implement BIDS-Apps interface

- CHANGES.txt
- mriqc/qc/anatomical.py
> [FIX] Skip QI2 computation if background does not show a noise distribution

- mriqc/qc/anatomical.py
> [ENH] Do not compute QI2 if masked noise is 0

- mriqc/__init__.py
- mriqc/reports/generators.py
- mriqc/utils/mriqc_run.py
> [ENH] Add logging to the group level

- mriqc/reports/generators.py
This dramatically reduces the size of created reports. Closes #210
> use GS to merge PDFs if available

- .pylintrc
- circle.yml
- mriqc/data/__init__.py
- mriqc/data/config.py
- mriqc/data/reports/individual.html
- mriqc/info.py
- mriqc/interfaces/qc.py
- mriqc/interfaces/viz.py
- mriqc/interfaces/viz_utils.py
- mriqc/qc/anatomical.py
- mriqc/qc/tests/test_anatomical.py
- mriqc/reports/generators.py
- mriqc/reports/utils.py
- mriqc/utils/misc.py
- mriqc/utils/mriqc_run.py
- mriqc/workflows/anatomical.py
- requirements.txt
- setup.py
Includes:
- Separation between individual and group reports (#205)
- New template for registration (solves -hopefully- #185).
- Added new IQMs: Fuzzy Overlap of tissue probability maps from FAST and those projected from MNI space.
- Improved (significantly) the head mask, particularly Mortamet's one masking out below the nasio-orbitofrontal plane, with a large FoV new mask.
- HTML Reports for anatomical - individual reports (#34)
> [ENH] Large refactoring of anatomical workflow

- mriqc/info.py
- mriqc/workflows/functional.py
With this PR, the new debug mode of reports is finished.
The designated flag in the command line is ```--verbose-reports```
Closes #204
> [ENH] Add verbose reports to functional workflow

- docker/Dockerfile_py27
- docker/Dockerfile_py35
- mriqc/data/reports/individual.html
- mriqc/info.py
- mriqc/interfaces/viz_utils.py
- mriqc/reports/individual.py
- mriqc/utils/misc.py
- mriqc/viz/fmriplots.py
- mriqc/workflows/functional.py
Example report with discarded volumes
> discard non steady state

- mriqc/interfaces/viz.py
- mriqc/interfaces/viz_utils.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- change colormaps of "noise" amps and standard deviation plots to "viridis_r" and "viridis" respectively
- move "noise" and "zoomed" maps to verbose only (only for functional plots)
> reports enhancements

- mriqc/data/reports/individual.html
- mriqc/reports/individual.py
Plots will now scale to 100% window size.
> autoscale plots

- docker/Dockerfile_py35
- mriqc/reports/individual.py
- mriqc/workflows/anatomical.py
> Fixes #255

- mriqc/viz/fmriplots.py
- mriqc/workflows/functional.py
The first NaN added in the time series was breaking the calculation
of ylims with numpy's max and min.
Also, done some work on the yticks and their labels
Closes #256
> [FIX] Calculation of ylims in confounds plots

- mriqc/workflows/utils.py
> [BUG] Problems with shape of FFT

- mriqc/interfaces/viz_utils.py
- mriqc/qc/anatomical.py
> [FIX] QI2 cannot be computed without enough voxels

- mriqc/data/reports/resources/boxplots.css
- mriqc/data/reports/resources/boxplots.js
- mriqc/info.py
> [ENH] Display all group reports inline, responsively

- mriqc/data/reports/individual.html
- mriqc/reports/individual.py
- mriqc/workflows/functional.py
> [ENH] Add notes on details of preprocessing

- mriqc/data/reports/group.html
- mriqc/data/reports/resources/boxplots.css
- mriqc/data/reports/resources/boxplots.js
- Separate boxes and strips (closes #228)
> [ENH] Improvements to group plots

- mriqc/interfaces/viz.py
- mriqc/workflows/functional.py
> [ENH] Mosaic of spikes: plot prev and next timepoints

- mriqc/interfaces/anatomical.py
- mriqc/interfaces/test/test_interfaces.py
- mriqc/qc/tests/test_anatomical.py
- setup.py
They don't use the brainweb anymore.
Added base for a QI1 test.
> [ENH] Simplify tests

- mriqc/data/reports/individual.html
- mriqc/interfaces/bids.py
- mriqc/reports/group.py
- mriqc/reports/individual.py
- mriqc/reports/utils.py
- mriqc/viz/fmriplots.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
... and in the header of the fMRI plot (#213)
Closes #194, since the TR and the PhaseEncodingDirection will be printed when available.
The other task, "Add right hand side ticks ..." has been superseded with the new composite fmriplot.
> [ENH] Show metadata in the individual reports

- mriqc/interfaces/viz.py
- mriqc/interfaces/viz_utils.py
> [FIX] Verbose-reports too dark

- mriqc/workflows/functional.py
> [ENH] Use ANTs for fMRI spatial normalization

- mriqc/bin/mriqc_run.py
- mriqc/data/reports/individual.html
- mriqc/data/reports/resources/boxplots.js
- mriqc/info.py
- mriqc/interfaces/__init__.py
- mriqc/interfaces/anatomical.py
- mriqc/interfaces/bids.py
- mriqc/interfaces/viz.py
- mriqc/interfaces/viz_utils.py
- mriqc/reports/group.py
- mriqc/reports/individual.py
- mriqc/reports/utils.py
- mriqc/utils/misc.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- mriqc/workflows/utils.py
Fixes #301 and derivated problems
> [ENH] Add a custom IQMFileSink for MRIQC

- mriqc/qc/functional.py
Use np.roll which is the appropriate tool. Calculate ghost as the mean
and signal as de median for robustness.
Fixes #303
> [ENH] Fix problem in computation of GSR

- circle.yml
- mriqc/interfaces/bids.py
- mriqc/reports/group.py
- mriqc/utils/misc.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
> [FIX] Read run_id as int

- mriqc/reports/individual.py
- mriqc/reports/utils.py
> [FIX] Generate individual report fails with no metadata

- mriqc/interfaces/functional.py
> Fix the FD threshold to be consistent with the plots and documentation

- mriqc/interfaces/functional.py
- mriqc/qc/anatomical.py
- mriqc/workflows/functional.py
Fixes #327 - Cast wm2max to float
Fixes #322
> Various casting problems

- mriqc/interfaces/viz.py
- mriqc/viz/fmriplots.py
- mriqc/viz/svg.py
- mriqc/viz/utils.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
Makes mosaics more consistent with the other plots, and fixes #273
> Migrate mriqc mosaics to nilearn

- mriqc/data/reports/individual.html
Fixes #314. In future releases we can consider adding bootstrap.js
to make a foldable panel as @chrisfilo suggested.
> Push metadata to the bottom of the report

- mriqc/utils/bids.py
> Fix BIDS queries

- mriqc/data/reports/group.html
Temporarily close #333 by getting the resources through the rawgit
proxy service.
> Make group reports totally self-contained

- mriqc/bin/mriqc_run.py
Now, it will be possible to run:
```
mriqc data/ out/ participant group
```
or
```
mriqc data/ out/ participant group --participant_label S002 S003
```
The original commandline for participant level without --participant_label
will run both levels, as before.
Closes #307
> [ENH] Command line accepts explicit participant and group invocation

- mriqc/workflows/anatomical.py
> [FIX] Remove non-repeatable step from pipeline

- circle.yml
- mriqc/bin/mriqc_run.py
- mriqc/info.py
- mriqc/utils/misc.py
... when there are no json files to be processed.
This PR also handles BIDS components more carefully when reading in the group csv file.
Closes #351
> Exit with meaningful error at group report creation

- circle.yml
- mriqc/bin/mriqc_run.py
> [RTM] Fixing group level reports.

- tests/circle_outputs.txt
> [RTM] second attempt to fix tests

- mriqc/utils/misc.py
> [RTM] respect the header when conforming

- mriqc/reports/group.py
> [FIX] Unicode error writing group reports

- mriqc/info.py
> [RTM] pybids version bump

- CHANGES.txt
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- requirements.txt
previously affine and warp transforms were applied in the wrong order
> [RTM] use composite transforms

- mriqc/interfaces/bids.py
Starting with crowdsourcing of IQMs
> [ENH] Add mriqc version (close #382) and input image hash (close #381)

- CHANGES.txt
- circle.yml
- mriqc/bin/mriqc_run.py
- requirements.txt
- tests/circle_outputs.txt
Allows generating reports like this one: https://854-54756129-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/logs/run_stats.log.html
> [ENH] Add --profile flag

- CHANGES.txt
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- Fix a bug causing EPI mask erosion to be essentially disabled
- Switch all ApplyTransformation to use FLOAT32
- Use 2mm targets for MNI coregistrations to improve performance
I am happy to split this into separate PRs is something is too controversial.
> [RTM] various fixes

- CHANGES.txt
- circle.yml
- mriqc/bin/mriqc_run.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- requirements.txt
Trying to make motion parameters estimates faster and more comparable with FMRIPREP.
> [RTM] various MC realated fixes

- docs/source/docker.rst
> [RTM] docs updates

- Dockerfile
Minor fixes to the current dockerfile, split from the parallelization branch.
> [ENH] Update Dockerfile

- circle.yml
> [FIX] Erroneous flag --n_proc in CircleCI

- circle.yml
After some debugging, I've found that the `-v /etc/localtime:/etc/localtime:ro` bit of the docker run commands was crashing docker run.
> [TST] Binding /etc/localtime stopped working in docker 1.9.1

- mriqc/qc/functional.py
> [DOC] Fix functional feature labels in documentation (docs_only)

- mriqc/bin/mriqc_run.py
Added messages for when levels start and successfully finish.
Close #487
> [ENH] Improved logging of mriqc_run

- mriqc/data/reports/individual.html
- mriqc/interfaces/bids.py
- mriqc/reports/individual.py
- mriqc/utils/misc.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
Adds the two new keywords `bids_meta` and `provenance` to the output IQM derivatives file.
> [ENH] Refactor derivatives

- mriqc/interfaces/webapi.py
Before submitting to MRIQCWebAPI
> [ENH] MRIQCWebAPI: hash fields that may have PI

- mriqc/bin/mriqc_clf.py
> [FIX] Allow --load-classifier option to be empty in mriqc_clf

- mriqc/bin/mriqc_run.py
> [ENH] Better error message when --participant_label is set

- .circleci/group.sh
- .circleci/participant.sh
- mriqc/__init__.py
- mriqc/bin/mriqc_run.py
- mriqc/qc/tests/__init__.py
- mriqc/reports/group.py
- mriqc/reports/individual.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/core.py
- mriqc/workflows/functional.py
> [FIX] Send logging output to stdout

- docs/environment.yml
- mriqc/__about__.py
- requirements.txt
Tracks progress on resolving nipype issue.
Related: nipy/nipype#2074 oesteban/nipype#5
I will open a niworkflows PR when the nipype fix is merged.
> [FIX] Import fixed niworkflows.nipype

- docs/environment.yml
- requirements.txt
Include nipy/nipype#2074
Follow-up to #562.
> [FIX] Pin to poldracklab/niworkflows master

- mriqc/bin/mriqc_clf.py
- mriqc/classifier/helper.py
- mriqc/classifier/sklearn/_split.py
- notebooks/Generalization.ipynb
This split strategy generates an StratifiedKFold split on the test dataset, and then adds all the samples of the train dataset into the all train splits of all folds.
This split strategy will be useful to confirm that lack of generalization is derived from a batch effect.
> [ENH] Add PartiallyHeldOutKFold and iterated version

- mriqc/bin/mriqc_run.py
- mriqc/utils/misc.py
> [FIX] Do not write provenance in group CSV

- Dockerfile
See https://github.com/singularityware/singularity/issues/795#issuecomment-314235821
> [RTM] run ldconfig

- Dockerfile
> [FIX] OMP_NUM_THREADS not defined in Docker image

- docs/requirements.txt
- mriqc/__about__.py
- requirements.txt
> [ENH] Pin niworkflows to stable release (docs_only)

- mriqc/data/reports/embed_resources/boxplots.js
This will allow to see the distribution while removing outliers
that force the range shown in the scatterplot.
Fixes #313
> [ENH] Clip outliers in FD and SPIKES group plots

- mriqc/bin/mriqc_run.py
- mriqc/data/reports/embed_resources/boxplots.js
- mriqc/qc/anatomical.py
- mriqc/qc/functional.py
Creates anchors in the output html of the docs, and hooks up the plot labels to those anchors.
> [ENH] Labels in group reports link to docs

- mriqc/reports/group.py
This bugfix closes #551.
With thanks to @jvarada and A. Dufford for reporting this.
> [FIX] Error formatting subject labels for group reports

- docs/environment.yml
- mriqc/__about__.py
- mriqc/bin/mriqc_run.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- requirements.txt
- tests/circle_T1w.txt
- tests/circle_bold.txt
Includes: nipy/nipype#2198, nipy/nipype#2200
Depends: poldracklab/niworkflows#197
> [RTM] PIN: Update niworkflows

- Dockerfile
Per reply from @oesteban  to Issue #647
> Recursively set read/Xecute permission for miniconda

- mriqc/__about__.py
- requirements.txt
> [FIX] Update niworkflows pin

- CHANGES.txt
- Dockerfile
- mriqc/__about__.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- mriqc/workflows/utils.py
> AFNI update

- mriqc/__about__.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/utils.py
- requirements.txt
> let 3dFWHMx calculate its own mask

- docs/source/docker.rst
(Only in one file... could be other -v's that need to be changed elsewhere.
> Fix documentation to use --version instead of -v

- docs/environment.yml
- docs/requirements.txt
- mriqc/__about__.py
- requirements.txt
> Updating niworkflows

- mriqc/interfaces/webapi.py
> enable T2w metrics uploads

- mriqc/workflows/anatomical.py
We've seen some memory related issues with FAST (especially for multisession datasets). This should help.
> Increase FAST memory limits

- mriqc/__about__.py
- requirements.txt
Testing grabbit/pybids refactor to verify incf/pybids#135 doesn't break MRIQC.
> PIN: pybids 0.5

- mriqc/__about__.py
- mriqc/data/reports/individual.html
- mriqc/reports/__init__.py
- mriqc/reports/individual.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- requirements.txt
> [ENH] Various improvements to reports

- mriqc/bin/mriqc_run.py
- mriqc/utils/bids.py
Fixes #732
Fixes #727
Fixes #619
> [FIX] BIDSLayout queries

- mriqc/data/reports/individual.html
- mriqc/reports/utils.py
* Collapsible metadata, IQMs, provenance.
* Added top navbar
* FIX show table after voting
> [ENH,FIX] Updates to individual reports, fix table after rating

- .circleci/config.yml
- mriqc/bin/mriqc_run.py
- mriqc/data/reports/individual.html
- mriqc/interfaces/bids.py
- mriqc/reports/individual.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
A completely new rating widget, compatible with the current Web API and that allows the user to fetch a json file with the rating.
> [ENH] New feedback widget

- mriqc/utils/misc.py
> [FIX] Preempt pandas resolving Path objects

- mriqc/bin/mriqc_run.py
> [FIX] Set matplotlib backend early

- mriqc/reports/individual.py
It fixes #754 
(Individual.py would crash with --fft-spikes-detector option.)
> Fixes bug in reports/individual.py.

- mriqc/bin/mriqc_run.py
> [FIX/DOC] Append new line after dashes in mriqc_run help text

- mriqc/data/reports/individual.html
- mriqc/workflows/functional.py
As noted in #784, this breaks BOLD submission.
> FIX: Correctly set WebAPI rating endpoint in BOLD reports.

- setup.cfg
Pinning niworkflows-0.10.3rc1, which contains poldracklab/niworkflows#381.
Fixes #779.
> FIX: FileNotFoundError when MELODIC (``--ica``) does not converge

- docs/source/docker.rst
References #666 :japanese_ogre: 
Similar to poldracklab/fmriprep#1856
> DOC: Docker db size warning

- mriqc/bin/mriqc_run.py
Missing space in `--ica` text
ANFI -> AFNI in --hmc-afni text
> Corrected a couple of typos in --help text

- mriqc/cli/parser.py
> FIX: omp_nthreads typo

- .circleci/config.yml
Following @mgxd's lead in https://github.com/nipreps/fmriprep/pull/2295.
> CI: Update machine images on Circle

- mriqc/cli/parser.py
- mriqc/cli/run.py
- mriqc/config.py
- mriqc/utils/debug.py
> ENH: Add --pdb option to make debugging easier

- mriqc/cli/parser.py
> FIX: Participant labels starting with ``[sub]`` cannot be used

- mriqc/cli/parser.py
> Tiny "Running mriqc" docs fix

- docs/source/install.rst
Added instructions to avoid Tcl's couldn't connect to display error to installation instructions.
> Fixes for #891

- mriqc/workflows/functional.py
Follows up on #925 with the functional workflow.
> FIX: Update dependencies and repair BOLD workflow accordingly

- mriqc/cli/parser.py
- mriqc/config.py
- setup.cfg
Do not index all modalities, and share a database file so indexing is not so slow.
> ENH: Optimize *PyBIDS*' layout initialization

- .maint/CONTRIBUTORS.md
I added full name, affiliation to my entry and moved it to the correct alpha by last name position in the list.
I hope this is correct.
> Updating contributor info per request

- mriqc/interfaces/anatomical.py
> FIX: Replace all deprecated ``nibabel.get_data()`` in anatomical module

- mriqc/interfaces/anatomical.py
- mriqc/qc/anatomical.py
Replaces #920, which I accidentally closed.
Resolves: #919.
> FIX: Inconsistent API in anatomical CNR computation

- Dockerfile
- mriqc/interfaces/datalad.py
> FIX: Major improvements to new datalad-based interface & perform within containers

- .codespellrc
- .github/workflows/codespell.yml
- CHANGES.rst
- mriqc/bin/labeler.py
- mriqc/cli/parser.py
- mriqc/cli/run.py
- mriqc/cli/workflow.py
- mriqc/config.py
- mriqc/data/fsexport.tcl
- mriqc/data/reports/embed_resources/boxplots.js
- mriqc/data/reports/individual.html
- mriqc/data/reports/resources/boxplots.js
- mriqc/data/tests/ds000005/dataset_description.json
- mriqc/engine/plugin.py
- mriqc/interfaces/anatomical.py
- mriqc/interfaces/webapi.py
- mriqc/qc/anatomical.py
- mriqc/qc/functional.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/utils.py
- setup.cfg
I did pay attention to changes in the code -- I think those should be safe/ok.
> Codespell: config, action, and typos fixed

- .maint/MAINTAINERS.md
Hi @mckenziephagen, please check your data and confirm you want to go ahead with your inclusion as a maintainer :)
> MAINT: Add McKenzie to the maintainers table

- .maint/CONTRIBUTORS.md
just following @welcome bot advice: https://github.com/nipreps/mriqc/pull/1057#issuecomment-1441353846
> Add myself to CONTRIBUTORS

- mriqc/config.py
- setup.cfg
Requires  bids-standard/pybids#936.
With special love to @yasseraleman.
> FIX: Preempt PyBIDS to spend time indexing non-BIDS folders

- setup.cfg
> MAINT: Update niworkflows pin to support newer ANTs releases

- mriqc/workflows/functional.py
This feature has been tested with anatomical images (#1020 & #1024) and it is now included in the functional workflow.
> ENH: Add DataLad getter to inputs of functional workflows

- mriqc/messages.py
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
The "building workflow" message had not been updated on the functional workflow, resulting on overflowing lists of bold files for large datasets.
> FIX: Uniformize building workflow message (anat vs. func)

- .maint/MAINTAINERS.md
Please check data and intent is okay with you :)
> MAINT: Move Zvi to maintainers list

- .maint/CONTRIBUTORS.md
- .maint/PIs.md
Please confirm data and intent are okay with you :)
> MAINT: Add Ariel to contributors and PIs

- .maint/CONTRIBUTORS.md
@psadil - please check data and intent is okay with you :)
> MAINT: Add Patrick Sadil to contributors

- .maint/CONTRIBUTORS.md
- .maint/MAINTAINERS.md
Please check both data and intent are okay by you :)
> MAINT: Move Eilidh from contributors to maintainers

- .circleci/config.yml
- mriqc/workflows/anatomical.py
- mriqc/workflows/functional.py
- pyproject.toml
Related: nipreps/nireports#51.
> MAINT: Update *NiReports* calls to upcoming interfaces API

- mriqc/workflows/anatomical/base.py
Reducing duplicity created with the rats' branch.
EDIT: Amends an oversight in my review :)
> ENH: Move templates' probsegs into individual at normalization

- Dockerfile
- README.rst
> ENH: Culminate dropping FSL as a dependency

- mriqc/data/bootstrap-dwi.yml
- mriqc/interfaces/diffusion.py
- mriqc/workflows/diffusion/base.py
- mriqc/workflows/diffusion/output.py
Also plot FA and ADC in the reports.
Requires: #1113.
> ENH: Add a basic DTI fitting into the diffusion workflow

- mriqc/data/bootstrap-dwi.yml
- mriqc/workflows/diffusion/output.py
Using nireports' simple before/after new interface.
> ENH: More compact of shell-wise summary statistic maps (avg/std)

- mriqc/interfaces/functional.py
> FIX: replace np.float by np.float64

- mriqc/__main__.py
- mriqc/bin/abide2bids.py
- mriqc/bin/fs2gif.py
- mriqc/bin/subject_wrangler.py
- mriqc/config.py
- mriqc/engine/plugin.py
- mriqc/instrumentation/__main__.py
- mriqc/interfaces/bids.py
- mriqc/interfaces/functional.py
- mriqc/interfaces/transitional.py
- mriqc/qc/functional.py
- mriqc/qc/tests/test_anatomical.py
- mriqc/reports/group.py
- mriqc/synthstrip/__main__.py
- mriqc/utils/misc.py
- mriqc/workflows/anatomical/base.py
- mriqc/workflows/functional/output.py
- mriqc/workflows/utils.py
Apply most [pyupgrade](https://github.com/asottile/pyupgrade) suggestions:
```
pyupgrade --py38-plus
```
> MAINT: apply suggestions from pyupgrade

- mriqc/workflows/anatomical/base.py
- mriqc/workflows/diffusion/base.py
- mriqc/workflows/functional/base.py
https://docs.astral.sh/ruff/rules/extraneous-parentheses/
> STY: Remove extraneous parentheses

- pyproject.toml
> DOC: Update sphinx pinned version to 5

- mriqc/cli/parser.py
- mriqc/cli/workflow.py
- mriqc/messages.py
This improves the initial logging so that the first message doesn't take a long while to signal MRIQC started.
> ENH: Improved logging and optimize early checkpoint on subjects

- mriqc/cli/parser.py
- mriqc/data/config.py
- mriqc/interfaces/common/ensure_size.py
- mriqc/reports/group.py
- mriqc/reports/individual.py
- mriqc/testing.py
> FIX: Revise the last two sloppy merges

- .maint/CONTRIBUTORS.md
@effigies - I meant `CONTRIBUTORS.md`
@yibeichan - can you also tell us your ORCID (in case you want us to mention it in publications, etc.)?
> MAINT: Update contributor affiliation in ``CONTRIBUTORS.md``

- docs/source/conf.py
- mriqc/qc/anatomical.py
This is a first step towards more careful handling of floating point numbers prior to extracting summary statistics.
> ENH: Revise summary stats extraction and include controlled roundings

- mriqc/interfaces/diffusion.py
- mriqc/qc/diffusion.py
Percentage of brain volume.
Related: #1216.
> ENH: Add FA-based IQMs (nans percentage and degenerate percentage)

- mriqc/interfaces/diffusion.py
- mriqc/workflows/diffusion/base.py
> ENH: Add b-vector angular deviations as IQMs

- mriqc/workflows/anatomical/base.py
> FIX: Duplicate node in anatomical workflow

- Dockerfile
- mriqc/cli/run.py
- mriqc/cli/workflow.py
- mriqc/config.py
> FIX: Handle ``NUMEXPR_MAX_THREADS`` like ``OMP_NUM_THREADS``

- mriqc/interfaces/diffusion.py
> FIX: Drift should not be estimated when less than three low-b volumes present

- mriqc/interfaces/diffusion.py
Addresses problem in diffusion workflow inserted with #1242.
> FIX: Sloppy merge

- .circleci/circle_T1w.txt
- .circleci/circle_bold.txt
- .circleci/config.yml
- mriqc/cli/parser.py
- mriqc/cli/run.py
- mriqc/config.py
Leverage the unique run uuid we generate. This PR also sets a fixed one for debugging.
> FIX: Make sure new logs and config file output are compatible with parallel processes

- mriqc/data/reports/embed_resources/boxplots.js
- mriqc/reports/group.py
> FIX: Enable group reports for DWI

- pyproject.toml
> Removed pre-commit from development dependencies

- mriqc/cli/version.py
- mriqc/config.py
> ENH: Allow moving the cache folder with an environment variable

- mriqc/utils/misc.py
- mriqc/workflows/functional/base.py
> ENH: Flatten multi-echo lists in circumstances that they fail

- mriqc/config.py
I wasn't sure whether some cases should be annotated or not (e.g., `a = int(something)` versus `a: int = int(something)`, which doesn't actually add any information). Decided to take a maximalist approach, let me know if there's some other heuristic I should follow.
> ENH: Added type hints to config module

- .maint/CONTRIBUTORS.md
Add JHLegarreta to contributors list following welcome bot message after PR got merged.
> DOC: Add JHLegarreta to contributors list

- mriqc/workflows/functional/base.py
> FIX: Set ``n_procs`` instead of ``num_threads`` on node ``apply_hmc``

- mriqc/cli/parser.py
> FIX: Normalize bids-filters' modality keys to be lowercase

- mriqc/interfaces/webapi.py
Addresses second error in https://github.com/nipreps/mriqc/issues/1302#issuecomment-2299771427
> ENH: Handle WebAPI timeouts more gently

- mriqc/cli/parser.py
> ENH: Enable writing crashfiles in compressed-pickle format

- docs/source/install.rst
> doc: Fix missing code block start

- mriqc/__init__.py
This has various positive effects
- states how mature project is (starting year)
- states that it is still being developed since there are recent changes (current year)
Outdated year was a problem as misguiding folks
> Provide a range of years ending with current for the copyright statement

- .maint/update_authors.py
- mriqc/bin/abide2bids.py
- mriqc/bin/fs2gif.py
- mriqc/bin/labeler.py
- mriqc/cli/version.py
- mriqc/config.py
- mriqc/interfaces/webapi.py
- mriqc/reports/group.py
- mriqc/tests/test_parser.py
- mriqc/workflows/diffusion/output.py
- pyproject.toml
Leave out `docs/notebooks` for now.
> Upgrade to ruff 0.9.1

- .maint/CONTRIBUTORS.md
@vferat please confirm you are okay with being added to the contributors list, and if so, that your details are correct.
> MAINT: Add @vferat to ``CONTRIBUTORS.md``

- mriqc/interfaces/anatomical.py
- mriqc/workflows/anatomical/base.py
> FIX: More reliable anatomical harmonization

- mriqc/cli/parser.py
Fix link about PyBIDS BIDS file filtering option.
Fixes #1393.
> DOC: Fix link about PyBIDS BIDS file filtering option

- .circleci/config.yml
X-Ref: https://github.com/nipreps/mriqc/issues/1318#issuecomment-2842785059
> MAINT: Execute ``deploy_docker`` with commits to master
