scripts/mriqcp.py

Command line setting --nthreads was not being honored.
I think one or two lonestar5 nodes may have burst into flames.

Update multiproc settings to use --nthreads

---

CHANGES.txt
mriqc/__init__.py
mriqc/interfaces/qc.py
mriqc/qc/functional.py
mriqc/workflows/functional.py

This commit fixes #127 and closes #125.
Now, full FD and DVARS are available in the outputnode of the functional workflow.

[ENH] Return full FD/DVARS

---

CHANGES.txt
docker/Dockerfile_py27
docker/Dockerfile_py35
mriqc/utils/mriqc_run.py

This PR wants to fix two problems:
1. The group level failed when no anatomical qc-json files were
found in the derivatives folder. Now, it will only issue a warning
2. The group level will automatically be executed if no --participant_label
was specified.
Closes #196

[FIX] More reliable group-reports stage

---

circle.yml
mriqc/utils/mriqc_run.py

Use ```--n_procs``` as of now. ```--nthreads``` will still work for a while.

[ENH] Deprecate --nthreads flag

---

mriqc/interfaces/viz_utils.py

Since image orientation is RAS, the X-axis is represented flipped (Right-to-left).
This PR fixes #229

[FIX] Fixes X-axis flip in mosaics

---

CHANGES.txt
docs/requirements.txt
mriqc/info.py
mriqc/interfaces/viz.py
mriqc/interfaces/viz_utils.py
mriqc/workflows/functional.py

Now, the EPI2MNI replacement using ANTs instead of BBR works OK. Tested on the datasets of the bootcamp.
This also fixes a bug that happened when plotting the mosaic of spikes.

[ENH] A functional implementation of registration with ANTS

---

mriqc/info.py

Updated to 0.0.4, this should fix #329 after releasing to Pypi.

Insert version requirement for niworkflows

---

CHANGES.txt
mriqc/info.py
mriqc/reports/group.py

[FIX] BOLD reports clipped IQMs after spikes_num

---

mriqc/utils/bids.py

Adds the possibility of using the star (*) wildcard to select participants
with the `--participant_label` argument. Before this, the default was
using the greedy search.
Now,
```
mriqc data/ out/ participant --participant_label 32322A
```
will match only `sub-32322A`. And
```
mriqc data/ out/ participant --participant_label 32322A*
```
will match `sub-32322A`, `sub-32322AB`, etc. As well as:
```
mriqc data/ out/ participant --participant_label "*32322A"
```
that will match `sub-32322A` and `sub-032322A`, but won't match
`sub-32322AB`. **Please note the use of quotes so that the shell
does not expand the star**.
Finally,
```
mriqc data/ out/ participant --participant_label "*32322A*"
```
will match all previous examples (`sub-32322A`, `sub-032322A`, and `sub-032322AB`).
Close #385

[FIX] Fixes greedy participant selection

---

circle.yml
docker/Dockerfile_py27
docker/Dockerfile_py35
docker/files/run_tests

change to use a non-root location to help with singularity

use non-root location

---

docker/Dockerfile_py27
docker/Dockerfile_py35

Makes it consistent with other dependencies and FMRIPREP and allows for injecting code when using Singularity.

[RTM] Install mriqc in site-packages (disable editable mode)

---

circle.yml

This skips all tests, but will set up the build environment. Useful to debug problems with our docker images interacting with circle (mount points, etc.). Also as a lightweight commit for builds with SSH enabled.

[ENH] Add build_only tag to circle builds

---

Dockerfile
circle.yml

~~~Creates a new tag (poldracklab/mriqc:circleci) that gets updated after every successful push. This should keep all the changes for following builds.~~~
~~~An original idea stolen from @effigies~~~
After testing, the best option is using the `docker save/load` trick.

[TST] Downgrade docker to 1.9.1 in circle (build_only)

---

Dockerfile

Since neurodebian does not maintain old packages, when they are
updated, the build is broken.
Fixes #581

[FIX] Remove versions of afni and fsl in Dockerfile

---

.circleci/participant.sh
CHANGES.txt
mriqc/bin/mriqc_run.py

Using parallelism with ANTs causes numerical instability on the calculated measures. The most sensitive metrics to this problem are the kurtosis calculations on the intensities of regions and qi_2.

[ENH] Change default --ants-nthreads

---

mriqc/workflows/functional.py

This PR fixes a typo in individual functional reports ("ouliers" y-axis label)

[ENH] Typo fix for individual functional reports

---

docs/source/docker.rst

and minor tweaks.  Addresses issue #689.

[ENH] Add warning about mounting relative paths

---

docs/source/conf.py
mriqc/__about__.py
mriqc/bin/mriqc_run.py
mriqc/interfaces/anatomical.py
mriqc/interfaces/bids.py
mriqc/interfaces/common.py
mriqc/interfaces/functional.py
mriqc/interfaces/transitional.py
mriqc/interfaces/viz.py
mriqc/interfaces/webapi.py
mriqc/workflows/anatomical.py
mriqc/workflows/functional.py
mriqc/workflows/utils.py
requirements.txt

Purges `niworkflows.nipype` in favor of `nipype`.
Pins poldracklab/niworkflows#241.
----
This is just to validate poldracklab/niworkflows#238. Should be a functionally inert refactor, so can wait for the next niworkflows release to actually update the pin.

RF: Resume external nipype dependency

---

.circleci/config.yml
mriqc/__about__.py
mriqc/bin/mriqc_run.py
mriqc/interfaces/anatomical.py
mriqc/interfaces/bids.py
mriqc/interfaces/common.py
mriqc/interfaces/functional.py
mriqc/interfaces/webapi.py
requirements.txt

Testing poldracklab/niworkflows#248.

PIN: nipype 1.1.0, niworkflows

---

mriqc/workflows/functional.py

Tested on https://openneuro.org/datasets/ds001338/versions/00001. Temporary workaround for https://github.com/nipy/nipype/issues/2548

Reduce tSNR memory requirements

---

mriqc/interfaces/bids.py

Fixes the path relative to the BIDS root calculated for each file, that will be used as pattern for writing out the results.
It worked for single-session datasets, but was broken for multi-session datasets.

[FIX] Calculate relative path with sessions

---

Dockerfile

Fixes the permissions for the "mriqc" python package in the Docker image so that any user can run it.
Currently, because mriqc is installed after the permissions for the python packages were changed in line 111:https://github.com/poldracklab/mriqc/blob/471d7bb8a6f1611bec813fd62175ea74494552af/Dockerfile#L111,
the package "mriqc" is not world readable, so the permissions for the package "mriqc" have to be reset again.

Fix permissions in the Docker image.

---

mriqc/__about__.py
requirements.txt

Builds are failing in CircleCI because the niworkflows>=0.5 breaks
backwards compatibility.

[FIX] Niworkflows pin <0.5

---

docs/source/running.rst

Just a tiny correction to documentation.
The previous link was broken.

[DOC] Update BIDS validation link.

---

docs/source/reports/group.rst
mriqc/bin/mriqc_run.py
mriqc/interfaces/webapi.py
requirements.txt

As described in #750 
webapi upload function will return bunch object instead of response in certain circumstances causing an AttributeError to be thrown. We should catch this.

[FIX] Catch uncaught exception in WebAPI upload.

---

mriqc/data/reports/individual.html
mriqc/workflows/functional.py

FIX: Correctly process values of rating widget

---

.circleci/config.yml
docs/source/conf.py
mriqc/qc/anatomical.py
setup.cfg

Similarly to poldracklab/fmriprep#1790, we are changing to the Python
3.7+ docker image to test and deploy the Pypi package since twine has
stopped support for python <3.6 since their latest relase 2.0.

CI: Use recent Python image to build packages

---

.circleci/config.yml
Dockerfile

Other parts may need to be updated too.

Update to latest Ubuntu Xenial tag

---

mriqc/_warnings.py
mriqc/config.py
mriqc/workflows/anatomical.py
mriqc/workflows/functional.py

The warnings are handled in two ways:
* If this is a release, ignore all warnings (MRIQC does not use Python's warnings module, but logging instead).
* If development, warnings.showwarning and warnings.warn are monkeypatched to redirect to the ``'py.warnings'`` logger. The logger writes to /dev/null, but that can we change for debugging purposes.
Related: poldracklab/fmriprep#1981

MAINT: Clear the clutter of warnings

---

mriqc/classifier/data.py
mriqc/workflows/functional.py

RF: Simplify comprehensions, using easy-to-read var names

---

mriqc/config.py

We just hit #844 with mriqc 0.15.2.
Looking at https://github.com/poldracklab/mriqc/blob/master/mriqc/cli/parser.py#L378 we thought we could work around that by setting `OMP_NUM_THREADS` to 1 while still using values other than 1 for `--nprocs`. Unfortunately that didn't work because `config.nipype.omp_nthreads` is always [set](https://github.com/poldracklab/mriqc/blob/master/mriqc/config.py#L249) to `os.cpu_count()`.
This PR checks if the OpenMP environment variable exists and defaults back to `os.cpu_count()` - which is a confusing choice anyway, because it will always trigger the config warning if someone uses `--nprocs` other than 1 or `os.cpu_count()`, right?

FIX: honor OMP_NUM_THREADS environment variable

---

mriqc/cli/version.py

Fixes #853.
Following nipreps/fmriprep#1830.

FIX: Skip version cache on read-only filesystems

---

.circleci/circle_T1w.txt
.circleci/circle_bold.txt
mriqc/cli/run.py
mriqc/utils/bids.py

ENH: Write derivatives metadata

---

mriqc/viz/misc.py

Matplotlib has changed the API of the [hist](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.hist.html) function.  The parameter `normed` has been deprecated in favor of `density`.  This appears to cause some problems depending on which version of matplotlib you use, see traceback below.
```
Traceback (most recent call last):
File "~/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
result["result"] = node.run(updatehash=updatehash)
File "~/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
result = self._run_interface(execute=True)
File "~/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
return self._run_command(execute)
File …
```

Change depricated 'normed' to 'density' in parameters to hist()

---

Dockerfile

Prefetch this image so that MRIQC works more smoothly with Singularity.

FIX: T2w image of MNI template unavailable in Singularity

---

mriqc/utils/bids.py

FIX: Set entity ``datatype`` in ``BIDSLayout`` queries

---

mriqc/workflows/functional.py
setup.cfg

This pull request implements the integration of the voxels at the edge of the brain (also called crown) in the carpet plot.
To do so, the interface to compute the crown mask has been integrated in the functional workflow.
IMPORTANT ! : This piece of code depends on the change in the niworkflow repositories commited under the pull request nipreps/niworkflows#651.

ENH: Update to new niworkflows' API, which adds the crown to the carpetplot

---

mriqc/config.py

Fix typo in multiproc configuration.
Nipype [expects `n_procs`](https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/multiproc.py#L127) and not `nprocs` here. Explains #931 . Tested with 0.16.1 and monitored thread count with and without patch. Seems to be working.

Nipype multiproc plugin expects n_procs and not nprocs

---

mriqc/cli/run.py
mriqc/config.py

So instead of locking the config file (across multiple threads, yikes) I decided to just make the config file name unique using `mktemp`, avoiding the write conflict. Should avoid #912, but trashes the work directory a little.

Make toml config unique, works around #912

---

mriqc/interfaces/anatomical.py
mriqc/workflows/anatomical.py

In rodents, the proportion of WM and CSF are much smaller than in humans, and the spatial distribution of WM in particular is much thinner. Additionally, switching from FAST to Atropos for segmentation (f0dae1a07a05ca5d69c1d305f46c602bb237908f) results in fewer voxels with WM probabilities > 0.9 in some subjects.
Thus, eroding segmentations (WM segments in particular) and high binarising thresholds was generating empty images that caused the summary statistics to fail in a subset of subjects from a large dataset of T2w images. The proposed changes only apply when the `--species` flag is not set to the default `human` so it shouldn't impact most use cases.

FIX: preserve WM segments in rodents

---

mriqc/cli/parser.py

This PR addresses a long-standing problem introduced with the config file. Since MRIQC uses the ``--profiler`` flag and it is not marked up with a ``dest="resource_monitor"`` for argparse, then the resource monitor of Nipype is never enabled.
Resolves: #459.

FIX: Resource profiler was broken with config file

---

mriqc/__main__.py
mriqc/cli/run.py
mriqc/config.py
setup.cfg

It seems that confining the workflow creation within an isolated process does not meaningfully help with the VM allocation while increasing the complexity horribly.
On the other hand, the config file has been made considerably more lightweight by using importlib metadata to check versions instead of importing packages, and the plugin instance (MultiProc and LegacyMultiProc) are now created at earlier states so workers are initialized with smaller memory fingerprint.

ENH: Revise plugin and workflow initialization

---

.circleci/config.yml
mriqc/cli/parser.py
mriqc/cli/run.py
mriqc/cli/workflow.py
mriqc/config.py
mriqc/engine/plugin.py
mriqc/instrumentation/__main__.py
mriqc/instrumentation/resources.py
mriqc/instrumentation/viz.py

Adds an instrumentation module which could be eventually packaged with nipype or standalone to keep track of resource utilization of mriqc.
For now, I'm testing the pattern and will try to write up some code to generate nice plots with the data.
cc/ @effigies @mgxd

ENH: Add instrumentation to monitor resources

---

mriqc/cli/parser.py

If this is accepted, we should probably propagate it to *fMRIPrep*.
Resolves: #849.

DOC: Improve documentation of ``--nprocs`` and ``--omp-nthreads``

---

mriqc/cli/parser.py
mriqc/config.py
mriqc/workflows/functional.py
mriqc/workflows/utils.py

*MRIQC* is not a preprocessing tool. Therefore, there is no point in offering customizations that, instead, will open up the workflow to greater analytical variability. Instead of adding knobs for users to play with, it is better to make a more complete reporting of outputs (e.g., #992).
This PR disregards both flags from now on.
Resolves: #965.

ENH: Deprecate ``--start-idx`` / ``--stop-idx``

---

mriqc/interfaces/anatomical.py
mriqc/interfaces/functional.py

Runs some minimal sanity checks on masks and input data before the metrics are extracted.
Resolves: #781.

FIX: Check sanity of input data before extracting IQMs

---

mriqc/data/reports/individual.html

Changes with this PR:
- Updates Bootstrapjs to version 5.0.2
- Updates jQuery to version 3.6.0
- Updates some components of bootstrap for the new version
- Convert the rating widget into a range slider allowing interval
ratings.
- Reduce the space the widget takes with an accordion
- Make the rating widget invisible at the start
- Add a field for comments and a slider for rater confidence
- Add a timer, which is also reported within the JSON object.
Resolves: #1007.
Resolves: #1008.
New look and feel:

ENH: New version of the rating widget

---

mriqc/cli/parser.py

Currently, rotational FD components are calculated as the displacement on the surface of a sphere with a radius of 50 mm, because it:
> is approximately the mean distance from the cerebral cortex to the center of the head
according to Power et al., 2012.
This is obviously not appropriate for rodents, so we would expect rat data to exaggerate the contribution of rotational movement in FD calculations.
The only adjustment (so far) is to adjust the default radius if the species is non-human. This is less trivial for rats than humans, since brains of the former are not spherical. In my experience, roll rotations are more likely to occur if the animal is fixed in place with ear and bite bars, so I set the radius to be half of the average lateral width for 90-day-old rats in Gefen et al. (2004; …

set rat-specific defaults for FD calculations

---

mriqc/cli/parser.py
mriqc/cli/run.py
mriqc/interfaces/datalad.py
mriqc/workflows/anatomical.py

This interface runs some heuristics and tries to ``datalad get`` those files that look like broken symlinks in a datalad dataset.
EDIT1: testing out for potential use in other contexts.
EDIT2: unfortunately, nipype seems to fail in unpickling the `nohash` metadata, so the interface shows as executing on the second run. If using `contents` cache, this should not break dependent nodes though.

ENH: Add a new ``DataladIdentityInterface``

---

mriqc/cli/parser.py
mriqc/config.py
mriqc/data/config-example.toml
mriqc/workflows/functional.py

Closes #998 by removing ability to correct for slice-timing (which had only worked for some acquisitions)

remove slice-timing correction

---

mriqc/synthstrip/cli.py

The calculation of the new shape within the preprocessing for SynthStrip was done in XYZ coordinates (i.e., extents for each physical axis were estimated and divided by the new 1mm pixel size). However, the new axis sizes did not account for data being stored with IJK -> XZY convention (corresponding to LIA).
This PR accounts for this miscalculation.
Resolves: #999.

FIX: SynthStrip preprocessing miscalculating new shape after reorientation

---

Dockerfile

ENH: Bump Docker base to latest release

---

mriqc/cli/parser.py

Indeed, when I was feeding the output of a python script within a bash loop, the ``--participant-label`` argument was picking several identifiers as a single input:
```
IFS=$'\n'; for i in $( python groups.py ); do mriqc /data/datasets/ds002790/ /data/derivatives/ds002790/mriqc-22.0.5 participant -m T1w --participant-label $i --nprocs 32 --omp-nthreads 16 --verbose-reports -w work --dsname AOMIC2 -vv --bids-database-dir /data/derivatives/ds002790/.bids/; done
```
The output of `python groups.py` is of this sort:
```
0117 0118 0119 0120
0121 0122 0123 0124
0125 0126 0127 0128
0129 0130 0131 0132
0133 0134 0135 0136
0137 0138 0139 0140
0141 0142 0143 0144
```
The idea is to run four subjects within each loop.
This bugfix is a more robust solution.
Revises: #1025.
/cc @mgxd @effigies

FIX: Better fix to the multi-argument ``--participant-label`` issue

---

mriqc/qc/anatomical.py

Complete the documentation of summary_stats() so it lists explicitly all the summary metrics output. Meaning it provides an explanation of what "summary\_\*\_n", "summary\_\*\_k" and "summary\_\*\_mad" represent.
Closes #1042

DOC : complete the documentation of summary_stats()

---

.circleci/config.yml
mriqc/cli/parser.py
mriqc/cli/workflow.py
mriqc/config.py
mriqc/utils/telemetry.py
setup.cfg

This add `migas` telemetry to the MRIQC workflow, which is enabled by default. A new option `--notrack` can be used to disable monitoring.

ENH: Add migas telemetry

---

mriqc/instrumentation/__main__.py
mriqc/instrumentation/resources.py

This was likely caused by a change in Python of how `Event()` is initialized.
Clearing the event before entering the loop seems necessary now.
In addition, a more reliable initialization of the logfile pathname is also done here.

FIX: Resource monitor would not ever start tracking

---

mriqc/cli/run.py
mriqc/cli/workflow.py

The final process status is not properly sent to migas, as the exit function is not registered correctly.
This mirrors the logic used in fmriprep.

FIX: Move telemetry atexit into entrypoint func

---

mriqc/qc/anatomical.py

This patch addresses this problem encountered in some occassions, where the mask on which summary stats are to be calculated is too small.
Fixes: #1048.
Fixes: #868.

FIX: Address non-empty take from empty axes (anatomical IQMs)

---

mriqc/workflows/anatomical.py
mriqc/workflows/functional.py

Usually, rodent brains are viewed in the coronal orientation, as is the convention from physical atlases.
This updates the mosaic viz functions to change the orientation when `species == rat`: coronal becomes the primary axis (instead of axial), while axial becomes the secondary axis (instead of sagittal)

FIX: orientation of visualisations when `species == "rat"`

---

mriqc/workflows/functional.py

The metadata node takes ~50s for large datasets.
In the meantime while we find a better solution (perhaps dropping PyBIDS), it's better to send the metadata node to the workers so execution doesn't get stuck.

FIX: Send metadata extraction to workers (functional workflow)

---

mriqc/workflows/anatomical.py
mriqc/workflows/functional.py
pyproject.toml

There's no need to index the BIDS folder repeatedly with each of these interfaces.
Requires: nipreps/niworkflows#788.

ENH: Optimize metadata gathering reusing ``BIDSLayout`` db

---

.circleci/circle_T1w.txt
.circleci/circle_bold.txt
mriqc/config.py
mriqc/tests/test_config.py

Optimize the BIDS database handling by generating it in the output folder. Users can reset it by just deleting it (or the full folder, if necessary).
Several processes can be managed robustly by generating the index cache on a temporary folder with a unique name.

FIX: BIDS database directory handling

---

mriqc/workflows/anatomical/output.py
mriqc/workflows/functional/output.py

Fix for bug that obstructs rodent pipeline, because PlotMosaic expects lists of orientations, not tuples.

fix: PlotMosaic expects lists, not tuples

---

mriqc/qc/anatomical.py

Ensure only bounded numbers are passed into the kernel density estimator.

FIX: Add protection for NaNs and INFs when calculating QI2

---

mriqc/cli/parser.py
mriqc/config.py

Although convenient, the user experience of the previous implementation was really bad and already surfacing issues. This should make caching less aggressive, and the new ``--bids-database-wipe`` flag make the clean-up operation more transparent.

FIX: Better handling of BIDS cached indexation

---

.github/workflows/pythonpackage.yml

This drops old pip and use of venv for build, and uses pipx for tools to eliminate some pip installs altogether.
It also drops the pip cache. This is generally not a bottleneck, and I'm guessing it's the cause of the space limitations @celprov mentioned in #1137.

CI: Simplify GitHub actions checks and update action versions

---

mriqc/workflows/diffusion/base.py

I've made the change to replace the reference node based on #1125 (thanks @effigies  for the instruction).  Here is what I did:
1. copied this [function](https://github.com/nipreps/fmriprep/blob/next/fmriprep/workflows/bold/reference.py) into `mriqc/workflows/diffusion/base.py`, just above `hmc_workflow`, named as `init_dmriref_wf`
2. removed the dummy scan calculation in `init_dmriref_wf`, because it's not used anywhere in the current context
3. changed the docsting to be less BOLD focused.
4. modified the node `dwi_reference_wf`
5. changed the corresponding connections with `dwi_reference_wf` in the workflow

FIX: Use simpler DWI reference workflow

---

mriqc/utils/misc.py

fix: bug in group level workflow
fix: mriqc._version is deprecated
Closes #1128

FIX: bug in group level workflow

---

mriqc/interfaces/diffusion.py
mriqc/workflows/diffusion/base.py

fix: The (val_bold, gen_avg, [("out_file", "in_file")]), connection appeared twice
fix : get_shells has no output named b_masks

FIX: bugs in dwi workflow

---

mriqc/data/bootstrap-anat.yml

ENH: Swap background and zoomed-in visualizations in anatomical reports

---

mriqc/reports/group.py

We need to complete the dictionary with the list of IQMs associated with dwi, but it is not known at the moment, so for now the temporary fix is to add the 'dwi' key associated with an empty list.
Linked to #1173.

FIX: temporary fix of the missing dwi key

---

mriqc/reports/individual.py

FIX: Incorrect plugin metadata passed to Report assembler

---

mriqc/workflows/functional/base.py

Only one FD timeserie is computed in a multi-echo dataset, unlike DVARS, quality, and outliers for which one timeserie per echo is computed.
Closes #1178

FIX: Remove FD as an ``iterfield`` in ``MapNode`` causing crash with ME-BOLD

---

mriqc/utils/bids.py

Currently, the name attribute in "dataset_description.json" in the MRIQC derivatives is always set to "MRIQC - MRI Quality Control"
I propose instead copying the name from the input dataset.

FIX: copy name attribute of dataset_description.json from input dataset 

---

Dockerfile

Implements [@effigies' solution](https://github.com/nipreps/mriqc/issues/1175#issuecomment-1917588140) leveraging Docker multi-staged builds.
Checked linked libraries within the Docker container:
```
$ ldd /usr/local/bin/dwidenoise
linux-vdso.so.1 (0x00007fff6db65000)
libmrtrix.so => /usr/local/bin/../lib/libmrtrix.so (0x00007f4e2b757000)
libstdc++.so.6 => /opt/conda/lib/libstdc++.so.6 (0x00007f4e2b574000)
libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f4e2b48d000)
libgcc_s.so.1 => /opt/conda/lib/libgcc_s.so.1 (0x00007f4e2b472000)
libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4e2b46d000)
libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f4e2b242000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4e2bac2000)
libz.so.1 => /opt/conda/lib/libz.so.1 …
```

FIX: Include ``dwidenoise`` within docker image

---

pyproject.toml

An oversight from the new DWI pipeline inclusion.

FIX: DIPY not listed as a dependency

---

mriqc/data/config.py
mriqc/interfaces/common/ensure_size.py
mriqc/reports/group.py
mriqc/reports/individual.py
mriqc/testing.py

``pkg_resources`` is deprecated as an API.

FIX: Move from ``pkg_resources`` to ``niworkflows.data.Loader``

---

mriqc/workflows/anatomical/base.py

Changed reversed to reverse in gradient_threshold function. Should address #1210

FIX: Typo in sorted(..., reverse=True) call

---

mriqc/interfaces/diffusion.py
mriqc/qc/diffusion.py
mriqc/qc/tests/test_diffusion.py
mriqc/workflows/diffusion/base.py

Enables the computation of spiking voxels (by shells or b-value cluster centers of "shell-ified-DSI") and its redux to percentage values.
Resolves: #1222.

ENH: Add computation of spiking voxels mask and percent IQMs

---

mriqc/data/bootstrap-dwi.yml
mriqc/interfaces/diffusion.py
mriqc/workflows/diffusion/base.py
mriqc/workflows/diffusion/output.py

ENH: Move from DTI to DKI with multishell data

---

mriqc/config.py

The layout is printed out as a string when writing the config file. The object's ``__repr__`` shows a summary of subjects and tasks, etc., which for large datasets can be very costly.
Rewriting the layout's ``__repr__`` effectively reduces runtime.
Resolves: #1236.
cc/ @effigies

FIX: Avert costly ``BIDSLayout.__repr__`` calls when saving config

---

mriqc/config.py
mriqc/workflows/diffusion/base.py

This is the counterpart of #1120 for DWI.
In the case of DWI, this is easier to implement since bvals is a file expected to sit next to the NIfTI volume and should contain one column per volume in the forth dimension of the image.

FIX: Exclude DWI runs with insufficient orientations or missing bvals

---

mriqc/cli/parser.py
mriqc/cli/run.py
mriqc/config.py
mriqc/engine/plugin.py
mriqc/workflows/diffusion/base.py

Resolves: #1244.
Required-by: #1120.

FIX: Revise config save/load and update inputs after dropping

---

mriqc/bin/dfcheck.py

MAINT: Prevent pandas-originating deprecation warning

---

mriqc/reports/group.py

When generating group reports, we were getting more of those:
```
/opt/conda/lib/python3.11/site-packages/mriqc/reports/group.py:242:
FutureWarning: Index.ravel returning ndarray is deprecated; in a future
version this will return a view on self.
datacols = dataframe.columns.ravel().tolist()
```
Resolves: #1042.
Partially-addressed-by: #1251.

MAINT: Clean up more ``FutureWarning`` issued by pandas

---

mriqc/data/config.py
mriqc/reports/group.py

FIX: Address issues that had broken the group reports

---

mriqc/config.py
pyproject.toml

This happened, e.g., when trying to run MRIQC on datasets with both single-echo and multi-echo runs or with filters where some array had mixed types (e.g., `part: [null, 'mag']`).
Resolves: #1264.

FIX: Bug in *toml* loader crashing with mixed arrays in config

---

mriqc/workflows/functional/base.py

`dataset` and `full_files` are lists containing lists of strings when multiecho runs are present. When attempting to create sets with multiecho runs MRIQC crashed.
Resolves: #1290.
Derived-from: #1282.

FIX: Multiecho fMRI crashing with 'unhashable type' errors

---

mriqc/tests/test_parser.py

ENH: Add test for the CLI parser

---

mriqc/cli/run.py
mriqc/tests/test_main.py

Add CLI entry point test.
Add `argv` to `main()` for easier testing.

ENH: Add CLI entry point test

---

pyproject.toml

I assume the pin comes from before outsourcing mriqc-learn. No need to keep it that tight and let other dependencies set their restrictions.

MAINT: Flexibilize pandas pinned version

---

mriqc/cli/parser.py
mriqc/cli/run.py
mriqc/config.py
mriqc/interfaces/bids.py
mriqc/interfaces/webapi.py
mriqc/utils/misc.py
mriqc/workflows/anatomical/base.py
mriqc/workflows/diffusion/base.py
mriqc/workflows/functional/base.py
mriqc/workflows/functional/output.py

Aggregate dataset-wise operations that typically traverse the list of input files (datalad get, extract biggest file size and metadata extraction) in a single step.
Resolves #1316.

ENH: Crawl dataset's metadata only once and before Nipype's workflow

---

mriqc/qc/diffusion.py

The diffusion pipeline's calculation of IQMs choked if the cc mask was too small. Added a counter-measure and issue a warning in this case.

ENH(dMRI): Deal gracefully with small CC masks

---

mriqc/interfaces/diffusion.py

Addresses the issue reported by @psadil with his proposed solution 1 (considering the slope and intercept).
cc/ @effigies for a correctness check.
Resolves: #1315.

FIX: Resolve numeric overflow in drift estimation node

---

mriqc/interfaces/bids.py
mriqc/interfaces/webapi.py
pyproject.toml

Replaces the standard `json` library with `orjson`, which is way faster
and more reliable in terms of encoding numpy objects (the main issue we
typically hit within *MRIQC*).
Incidentally, this PR fixes an import of `simplejson`, which was not
listed as a dependency.
Related-to: https://github.com/nipreps/mriqc/issues/1302.
Closes: https://github.com/nipreps/mriqc/issues/546.
Closes: https://github.com/nipreps/mriqc/issues/1089.
Closes: https://github.com/nipreps/mriqc/issues/1133.

ENH: Use ``orjson`` to serialize JSON, addressing Numpy serialization issues

---

mriqc/interfaces/webapi.py

FIX: Passing ``bytes`` into ``str.join()``

---

.github/workflows/pythonpackage.yml
mriqc/bin/labeler.py
mriqc/cli/parser.py
mriqc/instrumentation/resources.py
mriqc/instrumentation/viz.py
mriqc/interfaces/anatomical.py
mriqc/interfaces/diffusion.py
mriqc/utils/bids.py
mriqc/utils/misc.py
pyproject.toml

- ENH: Remove redundant DIPY function
- STYLE: Fix style warnings raised by latest ruff release
- ENH: Require Python >= 3.9

ENH: Remove redundant DIPY function

---

mriqc/cli/run.py

Fix elapsed runtime format: the `strftime` function `%H` format specifier only supports 0–23 hours (for a single day), thus, when the time exceeds 24 hours, the hours component resets to 0.
This patch set computes the elapsed time (per participant and for the entire run), builds a `datetime.timedelta` instance and formats the elapsed time following the `%Hh %Mmin %Ss` formatting using a function created for that purpose.
Do not call `time.gmtime` as when reporting the elapsed time we are not interested in the UTC time format.

BUG: Fix elapsed runtime format

---

.circleci/config.yml
Dockerfile

FIX: Containers report wrong version

---

docs/source/usage.rst

Add a HPC troubleshooting section to the documentation

---

mriqc/interfaces/webapi.py

With the new JSON library, ``dumps()`` seems to return bytes. Here we decode the output of ``dumps()``, ensuring the output is converted into text.
This effectively should address the issue linked below.
Resolves: #1352.

FIX: Decode bytes to produce a string

---

Dockerfile

This finally resolves the problem of a wrong version being set in container images.
Resolves: #1354.
Overrides: #1357.

FIX: Containers report wrong version (revision)

---

docs/source/usage.rst

Complements: nipreps/nipreps.github.io#48
Amends: #1349.
Relates-to: #1367.
Resolves: #1170.

DOC: Continue moving documentation to the *NiPreps*'s site

---

pyproject.toml

Specify Python version for `ruff`: use Python 3.10 as a reasonable choice.
Fixes:
```
ruff
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```
raised for example at:
https://github.com/nipreps/mriqc/actions/runs/12795005155

ENH: Specify Python version for `ruff`

---

.github/workflows/pythonpackage.yml
pyproject.toml

Remove additional `setup-python` action in GHA workflow file, as Python is available through `pipx`.
Fixes:
```
ruff
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```
raised for example at:
https://github.com/nipreps/mriqc/actions/runs/12795005155
Also, revert the change introduced in commit 5cf7010 that unsuccessfully intended to fix the warning.

ENH: Remove additional `setup-python` action in GHA workflow file
